apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: statefulset-reader
rules:
  - apiGroups: [""]
    resources: ["statefulsets", "pods"]
    verbs: ["get", "watch", "list"]
