apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-statefulsets
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kv
    apiGroup: ""
roleRef:
  kind: Role
  name: statefulset-reader
  apiGroup: rbac.authorization.k8s.io
