apiVersion: v1
kind: Service
metadata:
  name: kv
  labels:
    app: kv
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: web
  clusterIP: None
  selector:
    app: kv
